Repository UMC-5th-Notation/CampusNote-Back, pull requests merged in 2024-02, with the labels that each got.

#12 feat: entity 및 크롤러 설계
  build.gradle
  src/main/java/UMC/campusNote/CampusNoteApplication.java
  src/main/java/UMC/campusNote/auditing/ApplicationAuditAware.java
  src/main/java/UMC/campusNote/auth/controller/AuthController.java
  src/main/java/UMC/campusNote/auth/dto/JoinReqDto.java
  src/main/java/UMC/campusNote/auth/dto/JoinResDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginReqDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginResDto.java
  src/main/java/UMC/campusNote/auth/dto/RefreshResDto.java
  src/main/java/UMC/campusNote/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/UMC/campusNote/auth/jwt/JwtProvider.java
  src/main/java/UMC/campusNote/auth/jwt/LogoutService.java
  src/main/java/UMC/campusNote/auth/redis/RedisProvider.java
  src/main/java/UMC/campusNote/auth/service/AuthService.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
  src/main/java/UMC/campusNote/classSideNote/ClassSideNote.java
  src/main/java/UMC/campusNote/common/code/ErrorReasonDTO.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/common/exception/ExceptionAdvice.java
  src/main/java/UMC/campusNote/common/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/UMC/campusNote/common/exception/handler/CustomAuthenticationEntryPoint.java
  src/main/java/UMC/campusNote/common/exception/handler/ExceptionHandler.java
  src/main/java/UMC/campusNote/common/s3/S3Provider.java
  src/main/java/UMC/campusNote/common/s3/dto/S3UploadRequest.java
  src/main/java/UMC/campusNote/config/AppConfig.java
  src/main/java/UMC/campusNote/config/RedisConfig.java
  src/main/java/UMC/campusNote/config/S3Config.java
  src/main/java/UMC/campusNote/config/SecurityConfig.java
  src/main/java/UMC/campusNote/config/SwaggerConfig.java
  src/main/java/UMC/campusNote/friend/Friend.java
  src/main/java/UMC/campusNote/lesson/Lesson.java
  src/main/java/UMC/campusNote/lesson/TestDataInit.java
  src/main/java/UMC/campusNote/lesson/controller/CrawlingController.java
  src/main/java/UMC/campusNote/lesson/converter/CrawlingHelper.java
  src/main/java/UMC/campusNote/lesson/converter/LessonConverter.java
  src/main/java/UMC/campusNote/lesson/dto/CrawlingRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDetailsDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDto.java
  src/main/java/UMC/campusNote/lesson/entity/Lesson.java
  src/main/java/UMC/campusNote/lesson/exception/CrawlingException.java
  src/main/java/UMC/campusNote/lesson/repository/LessonRepository.java
  src/main/java/UMC/campusNote/lesson/service/CrawlingService.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/main/java/UMC/campusNote/mapping/UserLesson.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonRepository.java
  src/main/java/UMC/campusNote/page/Page.java
  src/main/java/UMC/campusNote/user/User.java
  src/main/java/UMC/campusNote/user/controller/UserController.java
  src/main/java/UMC/campusNote/user/entity/Permission.java
  src/main/java/UMC/campusNote/user/entity/Role.java
  src/main/java/UMC/campusNote/user/entity/User.java
  src/main/java/UMC/campusNote/user/repository/UserRepository.java
  src/main/java/UMC/campusNote/user/service/UserService.java
  src/test/java/UMC/campusNote/lesson/repository/LessonRepositoryTest.java
  src/test/java/UMC/campusNote/lesson/service/CrawlingServiceTest.java
Labels: ✨feature

#16 Feat : 수업별 사이드 노트 설계
  .gitignore
  build.gradle
  src/main/java/UMC/campusNote/CampusNoteApplication.java
  src/main/java/UMC/campusNote/audio/Audio.java
  src/main/java/UMC/campusNote/classSideNote/controller/ClassSideNoteController.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteRequest.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteResponse.java
  src/main/java/UMC/campusNote/classSideNote/entity/ClassSideNote.java
  src/main/java/UMC/campusNote/classSideNote/exception/ClassSideNoteException.java
  src/main/java/UMC/campusNote/classSideNote/repository/ClassSideNoteRepository.java
  src/main/java/UMC/campusNote/classSideNote/service/ClassSideNoteService.java
  src/main/java/UMC/campusNote/classSideNote/status/ClassSideNoteErrorStatus.java
  src/main/java/UMC/campusNote/common/ApiResponse.java
  src/main/java/UMC/campusNote/common/BaseEntity.java
  src/main/java/UMC/campusNote/common/code/BaseCode.java
  src/main/java/UMC/campusNote/common/code/BaseErrorCode.java
  src/main/java/UMC/campusNote/common/code/ErrorReasonDTO.java
  src/main/java/UMC/campusNote/common/code/ReasonDTO.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/common/exception/ExceptionAdvice.java
  src/main/java/UMC/campusNote/common/exception/GeneralException.java
  src/main/java/UMC/campusNote/friend/Friend.java
  src/main/java/UMC/campusNote/image/Image.java
  src/main/java/UMC/campusNote/lesson/Lesson.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/main/java/UMC/campusNote/lessonNote/LessonNote.java
  src/main/java/UMC/campusNote/mapping/UserLesson.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/note/Note.java
  src/main/java/UMC/campusNote/page/Page.java
  src/main/java/UMC/campusNote/user/User.java
  src/main/resources/application.properties
Labels: ✨feature

#29 Feature/14
  build.gradle
  src/main/java/UMC/campusNote/CampusNoteApplication.java
  src/main/java/UMC/campusNote/classSideNote/controller/ClassSideNoteController.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteRequest.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteResponse.java
  src/main/java/UMC/campusNote/classSideNote/entity/ClassSideNote.java
  src/main/java/UMC/campusNote/classSideNote/exception/ClassSideNoteException.java
  src/main/java/UMC/campusNote/classSideNote/repository/ClassSideNoteRepository.java
  src/main/java/UMC/campusNote/classSideNote/service/ClassSideNoteService.java
  src/main/java/UMC/campusNote/classSideNote/status/ClassSideNoteErrorStatus.java
  src/main/java/UMC/campusNote/common/code/ErrorReasonDTO.java
  src/main/java/UMC/campusNote/common/exception/ExceptionAdvice.java
  src/main/java/UMC/campusNote/friend/Friend.java
  src/main/java/UMC/campusNote/lesson/Lesson.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/main/java/UMC/campusNote/mapping/UserLesson.java
  src/main/java/UMC/campusNote/user/User.java
Labels: duplicate, ✨feature

#30 fix : 중복된 entity 클래스 삭제
  src/main/java/UMC/campusNote/classSideNote/ClassSideNote.java
  src/main/java/UMC/campusNote/classSideNote/entity/ClassSideNote.java
  src/main/java/UMC/campusNote/classSideNote/service/ClassSideNoteService.java
  src/main/java/UMC/campusNote/common/code/ErrorReasonDTO.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/lesson/Lesson.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/main/java/UMC/campusNote/mapping/UserLesson.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/note/Note.java
  src/main/java/UMC/campusNote/page/Page.java
  src/main/java/UMC/campusNote/user/User.java
Labels: bug, duplicate

#32 [REFACTOR] 관련 api 수정
  build.gradle
  src/main/java/UMC/campusNote/CampusNoteApplication.java
  src/main/java/UMC/campusNote/auditing/ApplicationAuditAware.java
  src/main/java/UMC/campusNote/auth/controller/AuthController.java
  src/main/java/UMC/campusNote/auth/dto/JoinReqDto.java
  src/main/java/UMC/campusNote/auth/dto/JoinResDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginReqDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginResDto.java
  src/main/java/UMC/campusNote/auth/dto/RefreshResDto.java
  src/main/java/UMC/campusNote/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/UMC/campusNote/auth/jwt/JwtProvider.java
  src/main/java/UMC/campusNote/auth/jwt/LogoutService.java
  src/main/java/UMC/campusNote/auth/redis/RedisProvider.java
  src/main/java/UMC/campusNote/auth/service/AuthService.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
  src/main/java/UMC/campusNote/classSideNote/ClassSideNote.java
  src/main/java/UMC/campusNote/common/code/ErrorReasonDTO.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/common/exception/ExceptionAdvice.java
  src/main/java/UMC/campusNote/common/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/UMC/campusNote/common/exception/handler/CustomAuthenticationEntryPoint.java
  src/main/java/UMC/campusNote/common/exception/handler/ExceptionHandler.java
  src/main/java/UMC/campusNote/config/AppConfig.java
  src/main/java/UMC/campusNote/config/RedisConfig.java
  src/main/java/UMC/campusNote/config/SecurityConfig.java
  src/main/java/UMC/campusNote/config/SwaggerConfig.java
  src/main/java/UMC/campusNote/friend/Friend.java
  src/main/java/UMC/campusNote/lesson/Lesson.java
  src/main/java/UMC/campusNote/lesson/TestDataInit.java
  src/main/java/UMC/campusNote/lesson/controller/CrawlingController.java
  src/main/java/UMC/campusNote/lesson/converter/CrawlingHelper.java
  src/main/java/UMC/campusNote/lesson/converter/LessonConverter.java
  src/main/java/UMC/campusNote/lesson/dto/CrawlingRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDetailsDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDto.java
  src/main/java/UMC/campusNote/lesson/entity/Lesson.java
  src/main/java/UMC/campusNote/lesson/exception/CrawlingException.java
  src/main/java/UMC/campusNote/lesson/repository/LessonRepository.java
  src/main/java/UMC/campusNote/lesson/service/CrawlingService.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/main/java/UMC/campusNote/mapping/UserLesson.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonRepository.java
  src/main/java/UMC/campusNote/page/Page.java
  src/main/java/UMC/campusNote/page/PageController.java
  src/main/java/UMC/campusNote/page/PageService.java
  src/main/java/UMC/campusNote/user/User.java
  src/main/java/UMC/campusNote/user/UserRepository.java
  src/main/java/UMC/campusNote/user/controller/UserController.java
  src/main/java/UMC/campusNote/user/entity/Permission.java
  src/main/java/UMC/campusNote/user/entity/Role.java
  src/main/java/UMC/campusNote/user/entity/User.java
  src/main/java/UMC/campusNote/user/repository/UserRepository.java
  src/main/java/UMC/campusNote/user/service/UserService.java
  src/test/java/UMC/campusNote/lesson/repository/LessonRepositoryTest.java
  src/test/java/UMC/campusNote/lesson/service/CrawlingServiceTest.java
Labels: ♻️ refactor

#35 feat: Login/SignUp 수정
  src/main/java/UMC/campusNote/auth/dto/JoinResDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginResDto.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
Labels: ✨feature

#26 feat: 수업 관련 Api 설계
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/service/LessonService.java
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: ✨feature

#39 Feat: 수업 관련 Api 설계
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/service/LessonService.java
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: ✨feature

#36 feat: 로그인/회원가입 기능 수정
  src/main/java/UMC/campusNote/auth/dto/JoinResDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginResDto.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
Labels: ✨feature

#41 Feat: 특정 수업 삭제 Api 설계
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/lesson/TestDataInit.java
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/exception/LessonException.java
  src/main/java/UMC/campusNote/lesson/service/LessonService.java
  src/main/java/UMC/campusNote/lessonDetail/LessonDetail.java
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: ✨feature

#40 feat: page API 설계
  src/main/java/UMC/campusNote/common/s3/dto/S3UploadRequest.java
  src/main/java/UMC/campusNote/note/Note.java
  src/main/java/UMC/campusNote/note/NoteRepository.java
  src/main/java/UMC/campusNote/page/controller/PageController.java
  src/main/java/UMC/campusNote/page/converter/PageConverter.java
  src/main/java/UMC/campusNote/page/dto/PageRequestDTO.java
  src/main/java/UMC/campusNote/page/dto/PageResponseDTO.java
  src/main/java/UMC/campusNote/page/entity/Page.java
  src/main/java/UMC/campusNote/page/repository/PageRepository.java
  src/main/java/UMC/campusNote/page/service/PageService.java
Labels: ✨feature

#43 #42 [FEAT] 녹음 파일 관련 API 기능 개발
  src/main/java/UMC/campusNote/audio/controller/AudioController.java
  src/main/java/UMC/campusNote/audio/dto/AudioResDto.java
  src/main/java/UMC/campusNote/audio/entity/Audio.java
  src/main/java/UMC/campusNote/audio/repository/AudioRepository.java
  src/main/java/UMC/campusNote/audio/service/AudioService.java
  src/main/java/UMC/campusNote/audio/service/AudioServiceImpl.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/common/s3/S3Provider.java
  src/main/java/UMC/campusNote/note/Note.java
  src/main/java/UMC/campusNote/note/NoteRepository.java
Labels: ✨feature

#50 feat: 강의노트 API 구현
  src/main/java/UMC/campusNote/audio/Audio.java
  src/main/java/UMC/campusNote/audio/controller/AudioController.java
  src/main/java/UMC/campusNote/audio/dto/AudioResDto.java
  src/main/java/UMC/campusNote/audio/entity/Audio.java
  src/main/java/UMC/campusNote/audio/repository/AudioRepository.java
  src/main/java/UMC/campusNote/audio/service/AudioService.java
  src/main/java/UMC/campusNote/audio/service/AudioServiceImpl.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/common/s3/S3Provider.java
  src/main/java/UMC/campusNote/common/s3/dto/S3UploadRequest.java
  src/main/java/UMC/campusNote/lesson/repository/LessonRepository.java
  src/main/java/UMC/campusNote/lessonNote/LessonNote.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonNoteRepository.java
  src/main/java/UMC/campusNote/note/controller/NoteController.java
  src/main/java/UMC/campusNote/note/converter/NoteConverter.java
  src/main/java/UMC/campusNote/note/dto/NoteRequestDTO.java
  src/main/java/UMC/campusNote/note/dto/NoteResponseDTO.java
  src/main/java/UMC/campusNote/note/entity/Note.java
  src/main/java/UMC/campusNote/note/repository/NoteRepository.java
  src/main/java/UMC/campusNote/note/service/NoteService.java
  src/main/java/UMC/campusNote/note/service/NoteServiceImpl.java
  src/main/java/UMC/campusNote/page/controller/PageController.java
  src/main/java/UMC/campusNote/page/converter/PageConverter.java
  src/main/java/UMC/campusNote/page/dto/PageRequestDTO.java
  src/main/java/UMC/campusNote/page/dto/PageResponseDTO.java
  src/main/java/UMC/campusNote/page/entity/Page.java
  src/main/java/UMC/campusNote/page/repository/PageRepository.java
  src/main/java/UMC/campusNote/page/service/PageService.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ✨feature

#52 feat: 노트 관련 API 개발
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/lessonNote/controller/LessonNoteController.java
  src/main/java/UMC/campusNote/lessonNote/converter/LessonNoteConverter.java
  src/main/java/UMC/campusNote/lessonNote/dto/LessonNoteRequestDTO.java
  src/main/java/UMC/campusNote/lessonNote/dto/LessonNoteResponseDTO.java
  src/main/java/UMC/campusNote/lessonNote/entity/LessonNote.java
  src/main/java/UMC/campusNote/lessonNote/repository/LessonNoteRepository.java
  src/main/java/UMC/campusNote/lessonNote/service/LessonNoteService.java
  src/main/java/UMC/campusNote/note/entity/Note.java
Labels: ✨feature

#60 refactor: audio 관련 dto, converter 통일화 (#59)
  src/main/java/UMC/campusNote/audio/controller/AudioController.java
  src/main/java/UMC/campusNote/audio/converter/AudioConverter.java
  src/main/java/UMC/campusNote/audio/dto/AudioResDto.java
  src/main/java/UMC/campusNote/audio/dto/AudioResponseDTO.java
  src/main/java/UMC/campusNote/audio/repository/AudioRepository.java
  src/main/java/UMC/campusNote/audio/service/AudioService.java
  src/main/java/UMC/campusNote/audio/service/AudioServiceImpl.java
Labels: ♻️ refactor

#65 refactor: user, friend 관련 dto, converter 통일화
  src/main/java/UMC/campusNote/audio/dto/AudioResDto.java
  src/main/java/UMC/campusNote/auth/controller/AuthController.java
  src/main/java/UMC/campusNote/auth/converter/AuthConverter.java
  src/main/java/UMC/campusNote/auth/dto/AuthRequestDTO.java
  src/main/java/UMC/campusNote/auth/dto/AuthResponseDTO.java
  src/main/java/UMC/campusNote/auth/dto/JoinReqDto.java
  src/main/java/UMC/campusNote/auth/dto/JoinResDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginReqDto.java
  src/main/java/UMC/campusNote/auth/dto/LoginResDto.java
  src/main/java/UMC/campusNote/auth/dto/RefreshResDto.java
  src/main/java/UMC/campusNote/auth/service/AuthService.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/friend/controller/FriendController.java
  src/main/java/UMC/campusNote/friend/converter/FriendConverter.java
  src/main/java/UMC/campusNote/friend/dto/FriendRequestDTO.java
  src/main/java/UMC/campusNote/friend/entity/Friend.java
  src/main/java/UMC/campusNote/friend/repository/FriendRepository.java
  src/main/java/UMC/campusNote/friend/service/FriendService.java
  src/main/java/UMC/campusNote/user/entity/User.java
  src/main/java/UMC/campusNote/user/repository/UserRepository.java
  src/test/java/UMC/campusNote/friend/controller/FriendControllerTest.java
  src/test/java/UMC/campusNote/friend/repository/FriendRepositoryTest.java
  src/test/java/UMC/campusNote/friend/service/FriendServiceTest.java
Labels: ♻️ refactor

#61 refactor: audio 관련 dto, converter 통일화 (#59) (#60)
  src/main/java/UMC/campusNote/audio/controller/AudioController.java
  src/main/java/UMC/campusNote/audio/converter/AudioConverter.java
  src/main/java/UMC/campusNote/audio/dto/AudioResDto.java
  src/main/java/UMC/campusNote/audio/dto/AudioResponseDTO.java
  src/main/java/UMC/campusNote/audio/repository/AudioRepository.java
  src/main/java/UMC/campusNote/audio/service/AudioService.java
  src/main/java/UMC/campusNote/audio/service/AudioServiceImpl.java
Labels: ♻️ refactor

#68 feat: CI/CD
  .github/workflows/gradle.yml
  Dockerfile
Labels: ✨feature

#70 refactor: user, friend 관련 dto, converter 통일화
  src/main/java/UMC/campusNote/auth/controller/AuthController.java
  src/main/java/UMC/campusNote/auth/converter/AuthConverter.java
  src/main/java/UMC/campusNote/auth/dto/AuthRequestDTO.java
  src/main/java/UMC/campusNote/auth/dto/AuthResponseDTO.java
  src/main/java/UMC/campusNote/auth/service/AuthService.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
  src/main/java/UMC/campusNote/friend/controller/FriendController.java
  src/main/java/UMC/campusNote/friend/dto/FriendRequestDTO.java
  src/main/java/UMC/campusNote/friend/service/FriendService.java
  src/test/java/UMC/campusNote/friend/controller/FriendControllerTest.java
  src/test/java/UMC/campusNote/friend/service/FriendServiceTest.java
Labels: ♻️ refactor

#72 refactor: user, friend 관련 dto, converter 통일화
  src/main/java/UMC/campusNote/auth/controller/AuthController.java
  src/main/java/UMC/campusNote/auth/converter/AuthConverter.java
  src/main/java/UMC/campusNote/auth/dto/AuthRequestDTO.java
  src/main/java/UMC/campusNote/auth/dto/AuthResponseDTO.java
  src/main/java/UMC/campusNote/auth/service/AuthServiceImpl.java
Labels: ♻️ refactor

#69 feat: docker+git action을 사용한 CI/CD (#33) (#68)
  .github/workflows/gradle.yml
  Dockerfile
Labels: ✨feature

#53 feat: 노트 API 구현
  src/main/java/UMC/campusNote/audio/controller/AudioController.java
  src/main/java/UMC/campusNote/audio/entity/Audio.java
  src/main/java/UMC/campusNote/audio/repository/AudioRepository.java
  src/main/java/UMC/campusNote/audio/service/AudioService.java
  src/main/java/UMC/campusNote/audio/service/AudioServiceImpl.java
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/image/Image.java
  src/main/java/UMC/campusNote/lesson/repository/LessonRepository.java
  src/main/java/UMC/campusNote/lessonNote/converter/LessonNoteConverter.java
  src/main/java/UMC/campusNote/lessonNote/entity/LessonNote.java
  src/main/java/UMC/campusNote/lessonNote/service/LessonNoteService.java
  src/main/java/UMC/campusNote/mapping/UserLessonNote.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonNoteRepository.java
  src/main/java/UMC/campusNote/note/NoteRepository.java
  src/main/java/UMC/campusNote/note/controller/NoteController.java
  src/main/java/UMC/campusNote/note/converter/NoteConverter.java
  src/main/java/UMC/campusNote/note/dto/NoteRequestDTO.java
  src/main/java/UMC/campusNote/note/dto/NoteResponseDTO.java
  src/main/java/UMC/campusNote/note/entity/Note.java
  src/main/java/UMC/campusNote/note/repository/NoteRepository.java
  src/main/java/UMC/campusNote/note/service/NoteService.java
  src/main/java/UMC/campusNote/note/service/NoteServiceImpl.java
  src/main/java/UMC/campusNote/page/converter/PageConverter.java
  src/main/java/UMC/campusNote/page/dto/PageResponseDTO.java
  src/main/java/UMC/campusNote/page/entity/Page.java
  src/main/java/UMC/campusNote/page/service/PageService.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ✨feature

#67 refactor: lesson 관련 dto, converter 통일화
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/lesson/controller/CrawlingController.java
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/converter/LessonConverter.java
  src/main/java/UMC/campusNote/lesson/dto/CrawlingRequest.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDetailsDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonRequestDTO.java
  src/main/java/UMC/campusNote/lesson/dto/LessonResponseDTO.java
  src/main/java/UMC/campusNote/lesson/service/CrawlingService.java
  src/main/java/UMC/campusNote/lesson/service/LessonService.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonRepository.java
  src/test/java/UMC/campusNote/lesson/service/CrawlingServiceTest.java
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: ♻️ refactor

#75 refactor: lesson 관련 dto, converter 통일화 (#67)
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/lesson/controller/CrawlingController.java
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/converter/LessonConverter.java
  src/main/java/UMC/campusNote/lesson/dto/CrawlingRequest.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDetailsDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonDto.java
  src/main/java/UMC/campusNote/lesson/dto/LessonRequestDTO.java
  src/main/java/UMC/campusNote/lesson/dto/LessonResponseDTO.java
  src/main/java/UMC/campusNote/lesson/service/CrawlingService.java
  src/main/java/UMC/campusNote/lesson/service/LessonService.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonRepository.java
  src/test/java/UMC/campusNote/lesson/service/CrawlingServiceTest.java
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: ♻️ refactor

#79 fix: LessonServiceTest 병합 충돌 해결
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: bug

#80 fix: LessonServiceTest 병합 충돌 해결 (#79)
  src/test/java/UMC/campusNote/lesson/service/LessonServiceTest.java
Labels: bug

#81 refactor: Note 관련 api 스웨거 명세 추가 (#77)
  src/main/java/UMC/campusNote/note/controller/NoteController.java
Labels: ♻️ refactor

#86 refactor: Lesson 관련 api 스웨거 명세 추가
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonRequestDTO.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ♻️ refactor

#87 refactor: Lesson 관련 api 스웨거 명세 추가 (#86)
  src/main/java/UMC/campusNote/lesson/controller/LessonController.java
  src/main/java/UMC/campusNote/lesson/dto/CustomLessonRequest.java
  src/main/java/UMC/campusNote/lesson/dto/LessonRequestDTO.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ♻️ refactor

#57 feat: 친구 추가 api
  src/main/java/UMC/campusNote/common/code/status/ErrorStatus.java
  src/main/java/UMC/campusNote/friend/controller/FriendController.java
  src/main/java/UMC/campusNote/friend/dto/AddFriendReqDto.java
  src/main/java/UMC/campusNote/friend/entity/Friend.java
  src/main/java/UMC/campusNote/friend/repository/FriendRepository.java
  src/main/java/UMC/campusNote/friend/service/FriendService.java
  src/main/java/UMC/campusNote/user/entity/User.java
  src/main/java/UMC/campusNote/user/repository/UserRepository.java
  src/test/java/UMC/campusNote/friend/controller/FriendControllerTest.java
  src/test/java/UMC/campusNote/friend/repository/FriendRepositoryTest.java
  src/test/java/UMC/campusNote/friend/service/FriendServiceTest.java
Labels: ✨feature

#71 refactor: page, lessonNote 관련 DTO, Converter 통일화
  src/main/java/UMC/campusNote/lessonNote/controller/LessonNoteController.java
  src/main/java/UMC/campusNote/lessonNote/converter/LessonNoteConverter.java
  src/main/java/UMC/campusNote/lessonNote/dto/LessonNoteResponseDTO.java
  src/main/java/UMC/campusNote/page/controller/PageController.java
  src/main/java/UMC/campusNote/page/converter/PageConverter.java
  src/main/java/UMC/campusNote/page/dto/PageRequestDTO.java
  src/main/java/UMC/campusNote/page/dto/PageResponseDTO.java
  src/main/java/UMC/campusNote/page/service/PageService.java
Labels: ♻️ refactor

#90 fix: develop conflict 해결
  src/main/java/UMC/campusNote/image/converter/ImageConverter.java
  src/main/java/UMC/campusNote/image/service/ImageService.java
Labels: bug

#91 fix: 충돌 해결
  src/main/java/UMC/campusNote/friend/repository/FriendRepository.java
  src/main/java/UMC/campusNote/friend/service/FriendService.java
  src/test/java/UMC/campusNote/friend/service/FriendServiceTest.java
Labels: bug

#92 refactor: classSideNote 관련 dto, converter 통일화 (#56)
  src/main/java/UMC/campusNote/classSideNote/controller/ClassSideNoteController.java
  src/main/java/UMC/campusNote/classSideNote/converter/ClassSideNoteConverter.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteRequest.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteRequestDTO.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteResponse.java
  src/main/java/UMC/campusNote/classSideNote/dto/ClassSideNoteResponseDTO.java
  src/main/java/UMC/campusNote/classSideNote/entity/ClassSideNote.java
  src/main/java/UMC/campusNote/classSideNote/service/ClassSideNoteService.java
Labels: ♻️ refactor

#96 refactor: 노트 API에서 유저레슨 조회 시 파라미터 semester->attendedSemester로 변경 (#95)
  src/main/java/UMC/campusNote/note/controller/NoteController.java
  src/main/java/UMC/campusNote/note/dto/NoteRequestDTO.java
  src/main/java/UMC/campusNote/note/service/NoteService.java
  src/main/java/UMC/campusNote/note/service/NoteServiceImpl.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ♻️ refactor

#99 [FEAT] 유저의 현재 학기 수정 API 개발
  src/main/java/UMC/campusNote/common/code/status/SuccessStatus.java
  src/main/java/UMC/campusNote/image/controller/ImageController.java
  src/main/java/UMC/campusNote/mapping/repository/UserLessonRepository.java
  src/main/java/UMC/campusNote/user/controller/UserController.java
  src/main/java/UMC/campusNote/user/converter/UserConverter.java
  src/main/java/UMC/campusNote/user/dto/UserRequestDTO.java
  src/main/java/UMC/campusNote/user/dto/UserResponseDTO.java
  src/main/java/UMC/campusNote/user/service/UserService.java
  src/main/java/UMC/campusNote/user/service/UserServiceImpl.java
Labels: ✨feature

#97 refactor: 노트 API에서 유저레슨 조회 시 파라미터 semester->attendedSemester로 변경 (#95…
  src/main/java/UMC/campusNote/note/controller/NoteController.java
  src/main/java/UMC/campusNote/note/dto/NoteRequestDTO.java
  src/main/java/UMC/campusNote/note/service/NoteService.java
  src/main/java/UMC/campusNote/note/service/NoteServiceImpl.java
  src/test/java/UMC/campusNote/note/service/NoteServiceImplTest.java
Labels: ♻️ refactor

#101 feat: 친구 조회/삭제 기능 완성 (#74)
  src/main/java/UMC/campusNote/friend/controller/FriendController.java
  src/main/java/UMC/campusNote/friend/converter/FriendConverter.java
  src/main/java/UMC/campusNote/friend/dto/AddFriendReqDto.java
  src/main/java/UMC/campusNote/friend/dto/FriendResponseDTO.java
  src/main/java/UMC/campusNote/friend/repository/FriendRepository.java
  src/main/java/UMC/campusNote/friend/service/FriendService.java
  src/test/java/UMC/campusNote/friend/controller/FriendControllerTest.java
  src/test/java/UMC/campusNote/friend/service/FriendServiceTest.java
Labels: ✨feature
